tpm: eventlog: Declare mapping_size __maybe_unused
Given that when CONFIG_EFI is not enabled, do_mapping is inherently
false. Thus, the mapping_size variable is set but remains unused,
resulting in a compilation warning.

Simply annotating it with __maybe_unused will resolve this compilation
warning.

[ Fix follow errors with clang-19 when W=1e: ]
  In file included from drivers/char/tpm/tpm1-cmd.c:21:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm1-cmd.o] Error 1
  make[8]: *** Waiting for unfinished jobs....
  In file included from drivers/char/tpm/tpm-dev-common.c:19:
  In file included from drivers/char/tpm/tpm.h:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm-dev-common.o] Error 1
  In file included from drivers/char/tpm/tpm2-cmd.c:14:
  In file included from drivers/char/tpm/tpm.h:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  In file included from drivers/char/tpm/tpm-dev.c:16:
  In file included from drivers/char/tpm/tpm-dev.h:6:
  In file included from drivers/char/tpm/tpm.h:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm-dev.o] Error 1
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm2-cmd.o] Error 1
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpmrm-dev.o] Error 1
  In file included from drivers/char/tpm/tpm-chip.c:24:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  In file included from drivers/char/tpm/tpm-sysfs.c:16:
  In file included from drivers/char/tpm/tpm.h:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm-chip.o] Error 1
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm-sysfs.o] Error 1
  In file included from drivers/char/tpm/tpm2-sessions.c:71:
  In file included from drivers/char/tpm/tpm.h:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm2-sessions.o] Error 1
  In file included from drivers/char/tpm/tpm-interface.c:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm-interface.o] Error 1
  In file included from drivers/char/tpm/tpm2-space.c:16:
  In file included from drivers/char/tpm/tpm.h:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm2-space.o] Error 1
  In file included from drivers/char/tpm/eventlog/tpm1.c:24:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/eventlog/tpm1.o] Error 1
  In file included from drivers/char/tpm/eventlog/common.c:20:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/eventlog/common.o] Error 1
  In file included from drivers/char/tpm/eventlog/tpm2.c:20:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/eventlog/tpm2.o] Error 1
  In file included from drivers/char/tpm/tpm_vtpm_proxy.c:24:
  In file included from drivers/char/tpm/tpm.h:28:
  ./include/linux/tpm_eventlog.h:167:6: error: variable 'mapping_size' set but not used [-Werror,-Wunused-but-set-variable]
    167 |         int mapping_size;
        |             ^
  1 error generated.
  make[8]: *** [scripts/Makefile.build:207: drivers/char/tpm/tpm_vtpm_proxy.o] Error 1
  make[7]: *** [scripts/Makefile.build:465: drivers/char/tpm] Error 2
  make[6]: *** [scripts/Makefile.build:465: drivers/char] Error 2
  make[6]: *** Waiting for unfinished jobs....

Suggested-by: Chen Linxuan <chenlinxuan@uniontech.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>