cpufreq: export sched_set_itmt_support and sched_set_itmt_core_prio
When "CONFIG_X86_ACPI_CPUFREQ" in the config is modified to "m",
there will be compilation errors:
ERROR: modpost: "sched_set_itmt_core_prio" [drivers/cpufreq/acpi-cpufreq.ko] undefined!
ERROR: modpost: "sched_set_itmt_support" [drivers/cpufreq/acpi-cpufreq.ko] undefined!
Therefore, it is necessary to export sched_set_itmt_support and
sched_set_itmt_core_prio.

Signed-off-by: LeoLiu-oc <leoliu-oc@zhaoxin.com>