MIPS: dec: Remove dec_irq_dispatch()
Commit 187933f23679 ("[MIPS] do_IRQ cleanup") introduced dec_irq_dispatch()
function. But Subsequent to commit 8f99a1626535 ("MIPS: Tracing: Add
IRQENTRY_EXIT section for MIPS"), the dec_irq_dispatch() function is
rendered superfluous. Remove it to eradicate compilation warnings.

[ Quoting Maciej W. Rozycki: ]

    It always has been, since its inception, see commit 187933f23679
  ("[MIPS] do_IRQ cleanup").

    Up to commit 8f99a16265353 ("MIPS: Tracing: Add IRQENTRY_EXIT section
  for MIPS") `do_IRQ' used to be a macro, that's why.  At the time `do_IRQ'
  was converted to a macro `dec_irq_dispatch' was created and previously
  this place used to call `do_IRQ' too.

    This cleanup should have been made along with commit 8f99a16265353, so
  it's pretty old a technical debt being sorted here.

[ Fix follow error with gcc-14 when -Werror: ]

arch/mips/dec/setup.c:780:25: error: no previous prototype for ‘dec_irq_dispatch’ [-Werror=missing-prototypes]
  780 | asmlinkage unsigned int dec_irq_dispatch(unsigned int irq)
      |                         ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [scripts/Makefile.build:207: arch/mips/dec/setup.o] Error 1
make[6]: *** [scripts/Makefile.build:465: arch/mips/dec] Error 2
make[5]: *** [scripts/Makefile.build:465: arch/mips] Error 2
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:1992: .] Error 2
make[3]: *** [debian/rules:74: build-arch] Error 2
dpkg-buildpackage: error: make -f debian/rules binary subprocess returned exit status 2
make[2]: *** [scripts/Makefile.package:126: bindeb-pkg] Error 2
make[1]: *** [/mnt/83364c87-f5ee-4ae8-b862-930f1bd74feb/Projects/CommitUpstream/LinuxKernel/Temp/linux/Makefile:1625: bindeb-pkg] Error 2
make: *** [Makefile:251: __sub-make] Error 2

Link: https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=187933f23679c413706030aefad9e85e79164c44
Link: https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8f99a162653531ef25a3dd0f92bfb6332cd2b295
Link: https://lore.kernel.org/all/alpine.DEB.2.21.2502220019210.65342@angie.orcam.me.uk/
Signed-off-by: WangYuli <wangyuli@uniontech.com>
---
Changelog:
 *v1->v2: More detailed commit message.