clk: cix: Add missing slab.h include
Add the missing "#include <linux/slab.h>" to fix follow errors:
  drivers/clk/cix/clk.c: In function ‘cix_uart_clocks_register’:
  drivers/clk/cix/clk.c:47:27: error: implicit declaration of function ‘kcalloc’ [-Werror=implicit-function-declaration]
     47 |         cix_uart_clocks = kcalloc(clk_count, sizeof(struct clk *), GFP_KERNEL);
        |                           ^~~~~~~
  drivers/clk/cix/clk.c:47:25: error: assignment to ‘struct clk **’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
     47 |         cix_uart_clocks = kcalloc(clk_count, sizeof(struct clk *), GFP_KERNEL);
        |                         ^
  drivers/clk/cix/clk.c: In function ‘cix_clk_disable_uart’:
  drivers/clk/cix/clk.c:73:17: error: implicit declaration of function ‘kfree’ [-Werror=implicit-function-declaration]
     73 |                 kfree(cix_uart_clocks);
        |                 ^~~~~
  cc1: all warnings being treated as errors

Fixes: 8b9beff06f8d ("clk: cix: add sky1-audss and acpi clk drivers.")
Signed-off-by: WangYuli <wangyuli@uniontech.com>