ASoC: cix: Add missing bitfield.h include
Add the missing "#include <linux/bitfield.h>" to fix follow errors:

  sound/soc/cix/cdns_i2s_sc.c: In function ‘lp_src_set’:
  sound/soc/cix/cdns_i2s_sc.c:257:28: error: implicit declaration of function ‘FIELD_PREP’ [-Werror=implicit-function-declaration]
    257 |                            FIELD_PREP(SKY1_AUDSS_CRU_INFO_I2S_LOOP_MAST, lp_src_index));
        |                            ^~~~~~~~~~
  cc1: all warnings being treated as errors

  sound/soc/cix/cdns_i2s_mc.c: In function ‘cdns_i2s_mc_tx_config’:
  sound/soc/cix/cdns_i2s_mc.c:236:21: error: implicit declaration of function ‘FIELD_PREP’ [-Werror=implicit-function-declaration]
    236 |         irq_mask |= FIELD_PREP(I2S_CID_CTRL_I2S_MASK,
        |                     ^~~~~~~~~~
  cc1: all warnings being treated as errors

Fixes: 4e80eeb10c03 ("ASoC: CIX: add sound controller&codec driver")
Signed-off-by: WangYuli <wangyuli@uniontech.com>